# Generated by Django 3.2.9 on 2022-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0026_mileagerevenuestandard_price_of_km'),
        ('accrual_deduction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrualdeduction',
            options={'verbose_name': 'Начисление/Вычет', 'verbose_name_plural': 'Начисления/Вычеты'},
        ),
        migrations.AddField(
            model_name='accrualdeduction',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cargoapp.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='accrualdeduction',
            name='type',
            field=models.CharField(choices=[('1', 'Начисление'), ('0', 'Вычет')], max_length=1, verbose_name='Тип начисления/вычета'),
        ),
    ]
