# Generated by Django 3.2.9 on 2022-03-14 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0026_mileagerevenuestandard_price_of_km'),
        ('accrual_deduction_app', '0004_remove_accrualdeduction_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualdeduction',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargoapp.driver', verbose_name='Водитель'),
        ),
    ]
