# Generated by Django 3.2.9 on 2022-03-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accrual_deduction_app', '0005_accrualdeduction_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualdeduction',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='accrualdeduction',
            name='upload_status',
            field=models.BooleanField(default=False, verbose_name='Статус выгрузки 1С'),
        ),
        migrations.AlterField(
            model_name='reasonofdeduction',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
    ]
