# Generated by Django 3.2.9 on 2022-01-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargoapp', '0020_alter_vehicle_nav_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutographDailyIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('maxSpeed', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Максимальная скорость')),
                ('averageSpeed', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Средняя скорость')),
                ('fuelConsumPerDay', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Расход по баку в л. за сутки')),
                ('fuelConsumPer100km', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Расход по баку в л. на 100 км')),
                ('fuelConsumPerMounth', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Месячный расход ДТ в л.')),
                ('rotationMAX', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Обороты макс')),
                ('parkCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество остановок')),
                ('parkCount5MinMore', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество остановок с вкл. ДВС более 5 минут')),
                ('hardBrakingCount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество резких торможений')),
                ('totalDistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Суточный пробег')),
                ('totalMounthDistance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Пробег за месяц')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargoapp.driver', verbose_name='Водитель')),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Дневные показатели автографа',
                'verbose_name_plural': 'Дневные показатели автографа',
            },
        ),
    ]
