# Generated by Django 3.2.9 on 2022-01-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='averageSpeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Средняя скорость'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='fuelConsumPer100km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расход по баку в л. на 100 км'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='fuelConsumPerDay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расход по баку в л. за сутки'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='fuelConsumPerMounth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Месячный расход ДТ в л.'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='maxSpeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная скорость'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='rotationMAX',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Обороты макс'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='totalDistance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Суточный пробег'),
        ),
        migrations.AlterField(
            model_name='autographdailyindicators',
            name='totalMounthDistance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег за месяц'),
        ),
    ]
