# Generated by Django 3.2.9 on 2022-01-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autographapp', '0002_auto_20220114_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autographdailyindicators',
            name='fuelConsumPerMounth',
        ),
        migrations.RemoveField(
            model_name='autographdailyindicators',
            name='totalMounthDistance',
        ),
    ]
