# Generated by Django 3.2.9 on 2022-01-28 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargoapp', '0020_alter_vehicle_nav_id'),
        ('autographapp', '0003_auto_20220114_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сolumnar',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='columnar_user', serialize=False, to='cargoapp.logistuser')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logist_user', to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
            ],
            options={
                'verbose_name': 'Колонный',
                'verbose_name_plural': 'Колонные',
            },
        ),
    ]
