# Generated by Django 3.2.9 on 2022-01-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autographapp', '0004_сolumnar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Сolumnar',
        ),
    ]
