# Generated by Django 3.2.9 on 2022-06-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autographapp', '0005_delete_сolumnar'),
    ]

    operations = [
        migrations.AddField(
            model_name='autographdailyindicators',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='autographdailyindicators',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
