# Generated by Django 3.2.9 on 2022-02-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=4000, verbose_name='Вопрос')),
                ('answer1', models.CharField(max_length=250, verbose_name='Ответ 1')),
                ('answer2', models.CharField(max_length=250, verbose_name='Ответ 2')),
                ('answer3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 3 (не обязательно)')),
                ('answer4', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 4 (не обязательно)')),
                ('answer5', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 5 (не обязательно)')),
                ('answer6', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 6 (не обязательно)')),
                ('answer7', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ 7 (не обязательно)')),
                ('correctAnswer', models.IntegerField(verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, max_length=2000, null=True, verbose_name='объяснение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Неповторимий элемент', max_length=100, verbose_name='Токен')),
                ('fio', models.CharField(max_length=100, verbose_name='Водитель')),
                ('number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('columnar', models.CharField(max_length=100, verbose_name='Kолонный')),
                ('carNumber', models.CharField(max_length=100, verbose_name='Гос номер')),
                ('carModel', models.CharField(max_length=100, verbose_name='Модель транспортного средства')),
                ('successfully', models.BooleanField(blank=True, verbose_name='Пройдено')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('selectedAnswers', models.CharField(help_text='ИД вопроса(1):Ответ, ИД вопроса(2):Ответ, ... ,ИД вопроса(N):Ответ', max_length=250, verbose_name='Выбранные ответы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
    ]
