# Generated by Django 3.2.9 on 2022-04-29 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargoapp', '0035_auto_20220428_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContragentInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
            },
        ),
        migrations.CreateModel(
            name='VehicleInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', '20%'), ('1', 'Без НДС')], max_length=2, verbose_name='Тип страховки')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С')),
                ('to_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Страховка автомобиля',
                'verbose_name_plural': 'Страховки автомобилей',
            },
        ),
    ]
