# Generated by Django 3.2.9 on 2022-04-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinsurance',
            name='contragent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance_app.contragentinsurance', verbose_name='Страховая компания'),
        ),
    ]
