# Generated by Django 3.2.9 on 2022-04-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_vehicleinsurance_contragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinsurance',
            name='type',
            field=models.CharField(choices=[('0', 'ОСАГО'), ('1', 'КАСКО')], max_length=2, verbose_name='Тип страховки'),
        ),
    ]
