# Generated by Django 3.2.9 on 2022-05-05 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0037_trailer'),
        ('insurance_app', '0004_auto_20220504_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrailerInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'ОСАГО'), ('1', 'КАСКО')], max_length=2, verbose_name='Тип страховки')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С')),
                ('to_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По')),
                ('contragent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance_app.contragentinsurance', verbose_name='Страховая компания')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance_app.ownerinsurance', verbose_name='Собственник')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargoapp.trailer', verbose_name='Полуприцеп')),
            ],
            options={
                'verbose_name': 'Страховка полуприцепа',
                'verbose_name_plural': 'Страховки полуприцепов',
            },
        ),
    ]
