# Generated by Django 3.2.9 on 2021-11-26 09:49

import cargoapp.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('psw', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='ПСВ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Логист',
                'verbose_name_plural': 'Логисты',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Код КЛАДР')),
                ('title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Наименование')),
                ('reduction', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Наименование')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование')),
                ('full_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование полное')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=10, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=14, null=True, verbose_name='ОГРН')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Юридический адрес')),
                ('nds', models.CharField(blank=True, choices=[('TP', '20%'), ('NO', 'Без НДС')], max_length=2, null=True, verbose_name='Состояние доставки')),
                ('bank_bik', models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Корр счет банка')),
                ('bank_title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование банка')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('car_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Гос номер')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С')),
                ('to_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По')),
                ('a_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка А')),
                ('b_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка В')),
                ('route_length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Протяженность маршрута')),
                ('route_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость маршрута')),
                ('expenses_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Прочие расходы')),
                ('expenses_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 2')),
                ('expenses_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 3')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость топлива')),
                ('pay_check', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Зарплата')),
                ('pure_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Чистый доход')),
                ('cost_of_km', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена за километр')),
                ('cost_of_platon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Платон')),
                ('day_count', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Количество дней')),
                ('items_count', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, verbose_name='Количетво мест')),
                ('request_img', models.ImageField(blank=True, default=None, null=True, upload_to=cargoapp.models.get_image_name, verbose_name='Скан Заявки')),
                ('loa_img', models.ImageField(blank=True, default=None, null=True, upload_to=cargoapp.models.get_image_name, verbose_name='Скан доверенности')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Вес, кг')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Объем, м3')),
                ('width', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Ширина, см')),
                ('height', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Высота, см')),
                ('depth', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Глубина, см')),
                ('request_number', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Номер заявки')),
                ('cargo_description', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Описание груза')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cargoapp.organization', verbose_name='Заказчик')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Мартшруты',
            },
        ),
    ]
