# Generated by Django 3.2.6 on 2021-08-23 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cargoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(blank=True, max_length=36, null=True, verbose_name='Идентификатор')),
                ('from_date', models.DateField(verbose_name='Дата По')),
                ('a_point', models.CharField(max_length=30, null=True, verbose_name='Точка А')),
                ('b_point', models.CharField(max_length=30, null=True, verbose_name='Точка В')),
                ('route_length', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Протяженность маршрута')),
                ('route_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость маршрута')),
                ('expenses_1', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Затрата 1')),
                ('expenses_2', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Затрата 2')),
                ('expenses_3', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Затрата 3')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Мартшруты',
            },
        ),
    ]
