# Generated by Django 3.2.6 on 2021-08-30 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Наименование')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('car_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Гос номер')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С')),
                ('to_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По')),
                ('a_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка А')),
                ('b_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка В')),
                ('route_length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Протяженность маршрута')),
                ('route_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость маршрута')),
                ('expenses_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 1')),
                ('expenses_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 2')),
                ('expenses_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 3')),
                ('driver', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель')),
                ('logist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
                ('vehicle', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Мартшруты',
            },
        ),
    ]
