# Generated by Django 3.2.9 on 2021-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0002_auto_20211126_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_corr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Корр счет банка'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер счета'),
        ),
    ]
