# Generated by Django 3.2.6 on 2021-08-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0002_driver_route_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistuser',
            name='psw',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='ПСВ'),
        ),
    ]
