# Generated by Django 3.2.6 on 2021-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0002_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='to_date',
            field=models.DateField(default=None, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_date',
            field=models.DateField(verbose_name='Дата С'),
        ),
    ]
