# Generated by Django 3.2.6 on 2021-09-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0003_logistuser_psw'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='Код КЛАДР')),
                ('title', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Наименование')),
                ('reduction', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Сокращение')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Прочие расходы'),
        ),
    ]
