# Generated by Django 3.2.6 on 2021-08-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0003_auto_20210823_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='third_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='route',
            name='a_point',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка А'),
        ),
        migrations.AlterField(
            model_name='route',
            name='b_point',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка В'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Затрата 1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Затрата 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Затрата 3'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата С'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Стоимость маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Протяженность маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Гос номер'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN'),
        ),
    ]
