# Generated by Django 3.2.6 on 2021-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0004_auto_20210824_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='expenses_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Затрата 1'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Затрата 2'),
        ),
        migrations.AlterField(
            model_name='route',
            name='expenses_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Затрата 3'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Протяженность маршрута'),
        ),
    ]
