# Generated by Django 3.2.9 on 2021-12-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0004_organization_is_contragent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('contragent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Контрагент', to='cargoapp.organization', verbose_name='Контрагент')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Организация', to='cargoapp.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
