# Generated by Django 3.2.9 on 2021-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0005_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
