# Generated by Django 3.2.9 on 2021-12-02 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0006_alter_contracts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contragent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contragent', to='cargoapp.organization', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to='cargoapp.organization', verbose_name='Организация'),
        ),
    ]
