# Generated by Django 3.2.9 on 2021-12-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0007_auto_20211202_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='route',
            name='height',
        ),
        migrations.RemoveField(
            model_name='route',
            name='items_count',
        ),
        migrations.RemoveField(
            model_name='route',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='route',
            name='width',
        ),
        migrations.AddField(
            model_name='route',
            name='banner_all',
            field=models.BooleanField(default=False, verbose_name='Растентовка полная'),
        ),
        migrations.AddField(
            model_name='route',
            name='banner_side',
            field=models.BooleanField(default=False, verbose_name='Растентовка бок'),
        ),
        migrations.AddField(
            model_name='route',
            name='control_penalty',
            field=models.BooleanField(default=False, verbose_name='Штраф контроля'),
        ),
        migrations.AlterField(
            model_name='route',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Вес, т'),
        ),
    ]
