# Generated by Django 3.2.9 on 2021-12-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0008_auto_20211202_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.contracts', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='route',
            name='contragent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='route_contragent', to='cargoapp.organization', verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='route',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='route_organization', to='cargoapp.organization', verbose_name='Организация'),
        ),
    ]
