# Generated by Django 3.2.9 on 2021-12-09 11:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0010_rename_client_route_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Действует с')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Пробег до ')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Пробег до ')),
                ('surcharge_2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (2 год)')),
                ('surcharge_3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (3 год)')),
                ('surcharge_4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (4 год)')),
                ('surcharge_5', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (5 год)')),
                ('surcharge_6', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (6 год)')),
                ('surcharge_7', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (7 годи далее)')),
            ],
            options={
                'verbose_name': 'Порог тарифов по ежемесячному пробегу',
                'verbose_name_plural': 'Пороги тарифов по ежемесячному пробегу',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='employment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='employment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.CreateModel(
            name='MileageRevenueStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Действует с')),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Норматив пробега')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Норматив выручки')),
                ('vehicle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Норматив по пробегу и выручке',
                'verbose_name_plural': 'Нормативы по пробегу и выручке',
            },
        ),
    ]
