# Generated by Django 3.2.9 on 2021-12-13 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0011_auto_20211209_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileagethresholds',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Пробег от '),
        ),
        migrations.AlterField(
            model_name='mileagethresholds',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Тариф '),
        ),
        migrations.CreateModel(
            name='DailyIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Пробег от ')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Тариф ')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargoapp.route', verbose_name='Ссылка на маршрут')),
            ],
            options={
                'verbose_name': 'Дневные показатели',
                'verbose_name_plural': 'Дневные показатели',
            },
        ),
    ]
