# Generated by Django 3.2.9 on 2021-12-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0012_auto_20211213_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyindicators',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cargoapp.driver', verbose_name='Ссылка на водителя'),
        ),
        migrations.AlterField(
            model_name='dailyindicators',
            name='mileage',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Протяженность'),
        ),
        migrations.AlterField(
            model_name='dailyindicators',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Стоимость'),
        ),
    ]
