# Generated by Django 3.2.9 on 2021-12-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0016_alter_dailyindicators_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyindicators',
            name='driver',
        ),
    ]
