# Generated by Django 3.2.9 on 2022-01-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0018_dailyindicators_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='nav_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyindicators',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='cargoapp.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='dailyindicators',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargoapp.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='mileagethresholds',
            name='surcharge_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Долата за стаж (7 год и далее)'),
        ),
    ]
