# Generated by Django 3.2.9 on 2022-01-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0019_auto_20220111_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nav_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Nav ID'),
        ),
    ]
