# Generated by Django 3.2.9 on 2022-01-31 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0021_logistuser_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='columnar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='columnar', to=settings.AUTH_USER_MODEL, verbose_name='Колонный'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='logist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='logist', to=settings.AUTH_USER_MODEL, verbose_name='Логист'),
        ),
    ]
