# Generated by Django 3.2.9 on 2022-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0022_auto_20220131_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='straight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Прямые (Сумма)'),
        ),
        migrations.AddField(
            model_name='route',
            name='straight_boolean',
            field=models.BooleanField(default=False, verbose_name='Прямые'),
        ),
    ]
