# Generated by Django 3.2.9 on 2022-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0024_alter_route_straight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileagerevenuestandard',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Норматив чистого дохода'),
        ),
    ]
