# Generated by Django 3.2.9 on 2022-04-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0026_mileagerevenuestandard_price_of_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Широта'),
        ),
    ]
