# Generated by Django 3.2.9 on 2022-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0027_auto_20220415_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Константа',
                'verbose_name_plural': 'Константы',
            },
        ),
    ]
