# Generated by Django 3.2.9 on 2022-04-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0031_alter_contracts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoute',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, verbose_name='Идентификатор')),
                ('from_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С')),
                ('to_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По')),
                ('a_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка А')),
                ('b_point', models.CharField(blank=True, max_length=30, null=True, verbose_name='Точка В')),
                ('route_length', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Протяженность маршрута')),
                ('route_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость маршрута')),
                ('expenses_1', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Прочие расходы')),
                ('expenses_2', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 2')),
                ('expenses_3', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Затрата 3')),
                ('straight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Чистый доход - прямые')),
                ('straight_boolean', models.BooleanField(default=False, verbose_name='Прямые')),
                ('fuel_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Стоимость топлива')),
                ('pay_check', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Зарплата')),
                ('pure_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Чистый доход')),
                ('cost_of_km', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена за километр')),
                ('cost_of_platon', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Платон')),
                ('day_count', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Количество дней')),
                ('request_img', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Скан Заявки')),
                ('loa_img', models.TextField(blank=True, default=None, max_length=100, null=True, verbose_name='Скан доверенности')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Вес, т')),
                ('request_number', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Номер заявки')),
                ('banner_all', models.BooleanField(default=False, verbose_name='Растентовка полная')),
                ('banner_side', models.BooleanField(default=False, verbose_name='Растентовка бок')),
                ('control_penalty', models.BooleanField(default=False, verbose_name='Штраф контроля')),
                ('cargo_description', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Описание груза')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargoapp.contracts', verbose_name='Договор')),
                ('contragent', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargoapp.organization', verbose_name='Контрагент')),
                ('driver', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargoapp.driver', verbose_name='Водитель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('logist', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Логист')),
                ('organization', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargoapp.organization', verbose_name='Организация')),
                ('vehicle', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cargoapp.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'historical Маршрут',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
