# Generated by Django 3.2.9 on 2022-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0032_historicalroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region_code',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Код субъекта'),
        ),
    ]
