# Generated by Django 3.2.9 on 2022-04-28 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0033_city_region_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='consignment',
            field=models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employment_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='from_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата С'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='to_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата С'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='employment_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 28), null=True, verbose_name='Дата приема на работу'),
        ),
    ]
