# Generated by Django 3.2.9 on 2022-04-28 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0034_auto_20220428_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='employment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С'),
        ),
        migrations.AlterField(
            model_name='historicalroute',
            name='to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='route',
            name='from_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата С'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата По'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='employment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата приема на работу'),
        ),
    ]
