# Generated by Django 3.2.9 on 2022-05-05 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0036_vehicle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.SlugField(max_length=36, unique=True, verbose_name='Идентификатор')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Гос номер')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Название')),
                ('release_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата выпуска')),
                ('consignment', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Партия')),
                ('employment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата приема на работу')),
            ],
            options={
                'verbose_name': 'Полуприцеп',
                'verbose_name_plural': 'Полуприцепы',
            },
        ),
    ]
