# Generated by Django 3.2.9 on 2022-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0037_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalroute',
            name='banner_a',
            field=models.BooleanField(default=False, verbose_name='Требуется растентовка А'),
        ),
        migrations.AddField(
            model_name='historicalroute',
            name='banner_b',
            field=models.BooleanField(default=False, verbose_name='Требуется растентовка Б'),
        ),
        migrations.AddField(
            model_name='historicalroute',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('0', 'Наличная'), ('1', 'Безналичная'), ('2', 'По заявке')], default='', max_length=1, null=True, verbose_name='Вид оплаты'),
        ),
        migrations.AddField(
            model_name='route',
            name='banner_a',
            field=models.BooleanField(default=False, verbose_name='Требуется растентовка А'),
        ),
        migrations.AddField(
            model_name='route',
            name='banner_b',
            field=models.BooleanField(default=False, verbose_name='Требуется растентовка Б'),
        ),
        migrations.AddField(
            model_name='route',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('0', 'Наличная'), ('1', 'Безналичная'), ('2', 'По заявке')], default='', max_length=1, null=True, verbose_name='Вид оплаты'),
        ),
    ]
