# Generated by Django 3.2.9 on 2022-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0038_auto_20220610_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='restrictions',
            field=models.BooleanField(default=False, verbose_name='Есть ограничения'),
        ),
    ]
