# Generated by Django 3.2.9 on 2022-07-07 09:22

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0039_driver_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name': 'Статус автомобиля',
                'verbose_name_plural': 'Стытусы автомобиля',
            },
        ),
    ]
