# Generated by Django 3.2.9 on 2022-07-07 09:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0041_vehicle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle_status',
            options={'verbose_name': 'Статус автомобиля', 'verbose_name_plural': 'Статусы автомобиля'},
        ),
        migrations.AlterField(
            model_name='vehicle_status',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None, verbose_name='Цвет'),
        ),
    ]
