# Generated by Django 3.2.9 on 2022-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0042_auto_20220707_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_of_last_scheduled_repair',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='scheduled_repair_mileage_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Межсервисный интервал'),
        ),
    ]
