# Generated by Django 3.2.9 on 2022-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_release_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinerelease',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='historicallinerelease',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='historicallinerelease',
            name='release_date',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='linerelease',
            name='begin_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='linerelease',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='linerelease',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска'),
        ),
    ]
