# Generated by Django 3.2.9 on 2022-06-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line_release_app', '0002_auto_20220620_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallinerelease',
            name='columnar',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Колонный'),
        ),
        migrations.AddField(
            model_name='linerelease',
            name='columnar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Колонный'),
        ),
    ]
